// Auto-generated file - DO NOT EDIT DIRECTLY
export type IconStyle = 'line' | 'filled' | 'color';

export type LineIconName = 
  | 'add'
  | 'animal-skin'
  | 'arrow-left-1'
  | 'arrow-right-1'
  | 'book-open'
  | 'bulleted-list'
  | 'calendar'
  | 'category'
  | 'chevron-down'
  | 'chevron-up'
  | 'clock'
  | 'close'
  | 'color-palette'
  | 'compare'
  | 'dotted-line-horizontal'
  | 'earth-locate'
  | 'expand'
  | 'face-id'
  | 'female'
  | 'filter-settings'
  | 'flip'
  | 'graph-stats-ascend'
  | 'graph-stats-descend'
  | 'hand-shake-heart'
  | 'hierarchy'
  | 'information-circle'
  | 'instagram'
  | 'kettlebell'
  | 'male'
  | 'map-marks'
  | 'move-back'
  | 'nav-menu'
  | 'origin'
  | 'outdoors-tree-valley'
  | 'pattern'
  | 'ruler'
  | 'scale'
  | 'search'
  | 'split-2'
  | 'split-3'
  | 'split'
  | 'tree'
  | 'turtle'
  | 'twitter'
  | 'two-arrows'
  | 'warning'
  | 'warp-shell-lower'
  | 'warp-shell-upper'
  | 'water-droplet';

export type FilledIconName = 
  | 'arrow-right'
  | 'checkmark-2'
  | 'checkmark'
  | 'close'
  | 'eyeball'
  | 'facebook'
  | 'flow-arrow-1'
  | 'hand-shake-heart'
  | 'linkedin'
  | 'lock'
  | 'marine-turtle'
  | 'outdoors-tree-valley'
  | 'trip-map-markers'
  | 'vegetables-salad'
  | 'warning'
  | 'youtube';

export type ColorIconName = 
  | 'algae'
  | 'fish-food'
  | 'fish-small'
  | 'fish'
  | 'frog'
  | 'prawn'
  | 'radiant'
  | 'seaweed'
  | 'shoal'
  | 'sleep'
  | 'sunny'
  | 'trout'
  | 'turtle-2'
  | 'turtle-basking'
  | 'turtle'
  | 'wood-log'
  | 'worm';

export type IconNameMap = {
  line: LineIconName;
  filled: FilledIconName;
  color: ColorIconName;
};
