-- ============================================================================
-- MIGRATION: Create Channels Table
-- ============================================================================
-- Channels are the main organizational structure for the community.
-- Think of them like subreddits or Discord channels - places where users
-- can post and discuss topics within a specific category.
-- ============================================================================

-- Create the channels table
CREATE TABLE public.channels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,              -- URL-friendly identifier (e.g., 'care', 'habitat')
  name TEXT NOT NULL,                     -- Display name (e.g., 'Care & Husbandry')
  description TEXT,                       -- Short description of the channel's purpose
  icon TEXT,                              -- Lucide icon name (e.g., 'megaphone', 'heart')
  category TEXT NOT NULL,                 -- Grouping category: 'general', 'care', 'conservation'
  sort_order INT DEFAULT 0,               -- Display order within the category
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed with initial channels
INSERT INTO public.channels (slug, name, description, icon, category, sort_order) VALUES
  ('announcements', 'Announcements', 'Official updates from Turterra about new features, events, and important news.', 'megaphone', 'general', 1),
  ('roadmap', 'Roadmap & Feedback', 'Share your ideas for Turterra and see what features we''re working on next.', 'map', 'general', 2),
  ('introductions', 'Introductions', 'New to Turterra? Introduce yourself and your shelled companions!', 'users', 'general', 3),
  ('help', 'Q&A Help Desk', 'Got questions? Ask anything turtle-related and get help from the community.', 'help-circle', 'general', 4),
  ('care', 'Care & Husbandry', 'Diet, feeding schedules, water quality, and general care discussions.', 'heart', 'care', 1),
  ('habitat', 'Habitat & Setup', 'Enclosure builds, tank setups, outdoor habitats, and equipment reviews.', 'home', 'care', 2),
  ('health', 'Health & Wellness', 'Health concerns, vet recommendations, shell care, and wellness tips.', 'activity', 'care', 3),
  ('conservation', 'Conservation', 'Conservation efforts, endangered species updates, and how to help.', 'leaf', 'conservation', 1),
  ('species-id', 'Species Identification', 'Help identifying turtle species from photos and field observations.', 'search', 'conservation', 2),
  ('wild-observations', 'Wild Observations', 'Share your wild turtle sightings, nesting observations, and field notes.', 'eye', 'conservation', 3);

-- Enable Row Level Security
ALTER TABLE public.channels ENABLE ROW LEVEL SECURITY;

-- Everyone can view channels (they're public)
CREATE POLICY "Channels are viewable by everyone"
  ON public.channels FOR SELECT USING (true);

-- Attach the updated_at trigger
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.channels
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
