-- ============================================================================
-- MIGRATION: Create Featured Species Table
-- ============================================================================
-- Tracks the weekly "Featured Species" shown on the community page.
-- Links to turtle_species for profile data and images.
-- Keeps a historical record of all previously featured species.
-- ============================================================================

CREATE TABLE public.featured_species (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  species_id INT NOT NULL,                      -- References turtle_species.id
  feature_start_date DATE NOT NULL,             -- Start of the feature period
  feature_end_date DATE NOT NULL,               -- End of the feature period
  description TEXT,                             -- Optional custom blurb for this feature
  is_active BOOLEAN DEFAULT FALSE,              -- Quick flag for the currently featured species
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  CONSTRAINT valid_date_range CHECK (feature_end_date >= feature_start_date)
);

-- Only one species should be active at a time
CREATE UNIQUE INDEX idx_featured_species_active
  ON public.featured_species (is_active) WHERE is_active = TRUE;

-- Index for date-based lookups
CREATE INDEX idx_featured_species_dates
  ON public.featured_species (feature_start_date DESC, feature_end_date);

ALTER TABLE public.featured_species ENABLE ROW LEVEL SECURITY;

-- Featured species are viewable by everyone
CREATE POLICY "Featured species are viewable by everyone"
  ON public.featured_species FOR SELECT USING (true);

-- Attach updated_at trigger
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.featured_species
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
