-- ============================================================================
-- MIGRATION: Create Comments Table
-- ============================================================================
-- Comments allow users to reply to posts and to other comments (threading).
-- Supports nested replies via parent_comment_id for threaded discussions.
-- ============================================================================

-- Create the comments table
CREATE TABLE public.comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  parent_comment_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE,  -- NULL for top-level comments
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  body TEXT NOT NULL,                     -- Markdown text
  score INT DEFAULT 0,                    -- Calculated from votes
  is_deleted BOOLEAN DEFAULT FALSE,       -- Soft delete (keeps thread structure)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for common query patterns
CREATE INDEX idx_comments_post ON public.comments(post_id, created_at ASC);
CREATE INDEX idx_comments_parent ON public.comments(parent_comment_id);
CREATE INDEX idx_comments_author ON public.comments(author_id);

-- Enable Row Level Security
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- All comments are publicly viewable
CREATE POLICY "Comments are viewable by everyone"
  ON public.comments FOR SELECT USING (true);

-- Only authenticated users can create comments, and only as themselves
CREATE POLICY "Authenticated users can create comments"
  ON public.comments FOR INSERT
  WITH CHECK (auth.uid() = author_id);

-- Users can only update their own comments
CREATE POLICY "Users can update their own comments"
  ON public.comments FOR UPDATE
  USING (auth.uid() = author_id)
  WITH CHECK (auth.uid() = author_id);

-- Attach the updated_at trigger
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.comments
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
