-- ============================================================================
-- MIGRATION: Create Posts Table
-- ============================================================================
-- Posts are the main content units in the community. Users create posts
-- within channels to share questions, discussions, showcases, and more.
-- ============================================================================

-- Create the posts table
CREATE TABLE public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_id BIGINT NOT NULL REFERENCES public.channels(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT,                              -- Markdown text (can be empty for image-only posts)
  post_type TEXT NOT NULL DEFAULT 'discussion',  -- 'discussion', 'question', 'showcase'
  image_urls TEXT[] DEFAULT '{}',         -- Array of Cloudinary image URLs
  score INT DEFAULT 0,                    -- Calculated from votes (upvotes - downvotes)
  hot_score DOUBLE PRECISION DEFAULT 0,   -- Reddit-style hot ranking score
  comment_count INT DEFAULT 0,            -- Denormalized count for performance
  is_pinned BOOLEAN DEFAULT FALSE,        -- Pinned posts appear at top of channel
  is_locked BOOLEAN DEFAULT FALSE,        -- Locked posts can't receive new comments
  is_draft BOOLEAN DEFAULT FALSE,         -- Drafts are only visible to the author
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for common query patterns
CREATE INDEX idx_posts_channel ON public.posts(channel_id, created_at DESC);
CREATE INDEX idx_posts_author ON public.posts(author_id);
CREATE INDEX idx_posts_hot ON public.posts(hot_score DESC);
CREATE INDEX idx_posts_score ON public.posts(score DESC, created_at DESC);
CREATE INDEX idx_posts_created ON public.posts(created_at DESC);

-- Enable Row Level Security
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- Published posts are visible to everyone; drafts only to their author
CREATE POLICY "Published posts are viewable by everyone"
  ON public.posts FOR SELECT
  USING (is_draft = FALSE OR auth.uid() = author_id);

-- Only authenticated users can create posts, and only as themselves
CREATE POLICY "Authenticated users can create posts"
  ON public.posts FOR INSERT
  WITH CHECK (auth.uid() = author_id);

-- Users can only update their own posts
CREATE POLICY "Users can update their own posts"
  ON public.posts FOR UPDATE
  USING (auth.uid() = author_id)
  WITH CHECK (auth.uid() = author_id);

-- Users can only delete their own posts
CREATE POLICY "Users can delete their own posts"
  ON public.posts FOR DELETE
  USING (auth.uid() = author_id);

-- Attach the updated_at trigger
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.posts
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
