-- ============================================================================
-- MIGRATION: Create Supporting Tables
-- ============================================================================
-- These tables support additional community features:
-- - Channel memberships: track which channels users have joined
-- - Saved posts: let users bookmark posts for later
-- - Hashtags: for trending topics and content discovery
-- - Community news: announcements and featured content
-- - Reports: content moderation system
-- ============================================================================

-- ============================================================================
-- CHANNEL MEMBERSHIPS
-- ============================================================================
-- Tracks which channels each user has joined
CREATE TABLE public.channel_memberships (
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  channel_id BIGINT NOT NULL REFERENCES public.channels(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, channel_id)
);

CREATE INDEX idx_memberships_channel ON public.channel_memberships(channel_id);

ALTER TABLE public.channel_memberships ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Memberships are viewable by everyone"
  ON public.channel_memberships FOR SELECT USING (true);

CREATE POLICY "Users can join channels"
  ON public.channel_memberships FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can leave channels"
  ON public.channel_memberships FOR DELETE USING (auth.uid() = user_id);

-- ============================================================================
-- SAVED POSTS
-- ============================================================================
-- Lets users bookmark posts to read or reference later
CREATE TABLE public.saved_posts (
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  saved_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, post_id)
);

ALTER TABLE public.saved_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can see their own saved posts"
  ON public.saved_posts FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can save posts"
  ON public.saved_posts FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can unsave posts"
  ON public.saved_posts FOR DELETE USING (auth.uid() = user_id);

-- ============================================================================
-- HASHTAGS
-- ============================================================================
-- Hashtags for trending topics and content organization
CREATE TABLE public.hashtags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,              -- Hashtag without the # (e.g., 'BoxTurtleCare')
  post_count INT DEFAULT 0,               -- Denormalized count for trending display
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_hashtags_name ON public.hashtags(name);
CREATE INDEX idx_hashtags_count ON public.hashtags(post_count DESC);

-- Junction table linking posts to hashtags (many-to-many)
CREATE TABLE public.post_hashtags (
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  hashtag_id BIGINT NOT NULL REFERENCES public.hashtags(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, hashtag_id)
);

ALTER TABLE public.hashtags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_hashtags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Hashtags are viewable by everyone"
  ON public.hashtags FOR SELECT USING (true);

CREATE POLICY "Post hashtags are viewable by everyone"
  ON public.post_hashtags FOR SELECT USING (true);

-- ============================================================================
-- COMMUNITY NEWS
-- ============================================================================
-- Official news items shown in the news carousel
CREATE TABLE public.community_news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT NOT NULL,                  -- Short preview text
  slug TEXT UNIQUE NOT NULL,              -- URL-friendly identifier
  body TEXT,                              -- Full article content (markdown)
  news_type TEXT NOT NULL DEFAULT 'announcement',  -- 'announcement', 'featured', 'partner_news', 'conservation'
  author_id UUID REFERENCES public.profiles(id),
  partner_name TEXT,                      -- For partner_news type
  image_url TEXT,                         -- Hero image
  is_published BOOLEAN DEFAULT FALSE,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_news_published ON public.community_news(published_at DESC) WHERE is_published = TRUE;

ALTER TABLE public.community_news ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Published news is viewable by everyone"
  ON public.community_news FOR SELECT USING (is_published = TRUE);

-- Attach updated_at trigger
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.community_news
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- ============================================================================
-- REPORTS
-- ============================================================================
-- Content moderation: users can report posts or comments
CREATE TABLE public.reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content_type TEXT NOT NULL CHECK (content_type IN ('post', 'comment')),
  content_id BIGINT NOT NULL,             -- ID of the reported post or comment
  reason TEXT NOT NULL CHECK (reason IN ('spam', 'harassment', 'misinformation', 'off_topic', 'inappropriate', 'self_harm', 'other')),
  details TEXT,                           -- Optional additional context
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'resolved', 'dismissed')),
  reviewed_by UUID REFERENCES public.profiles(id),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_reports_status ON public.reports(status, created_at DESC);

-- Prevent duplicate reports from the same user for the same content
CREATE UNIQUE INDEX idx_unique_report ON public.reports(reporter_id, content_type, content_id)
  WHERE status IN ('pending', 'reviewed');

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can create reports"
  ON public.reports FOR INSERT WITH CHECK (auth.uid() = reporter_id);

CREATE POLICY "Users can view their own reports"
  ON public.reports FOR SELECT USING (auth.uid() = reporter_id);
