-- ============================================================================
-- MIGRATION: Create Votes Table
-- ============================================================================
-- Votes allow users to upvote (+1) or downvote (-1) posts and comments.
-- A user can only have one vote per post/comment (enforced by unique constraints).
-- ============================================================================

-- Create the votes table
CREATE TABLE public.votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE,
  comment_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE,
  value SMALLINT NOT NULL CHECK (value IN (-1, 1)),  -- -1 for downvote, 1 for upvote
  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Each user can only vote once per post
  CONSTRAINT unique_post_vote UNIQUE (user_id, post_id),
  -- Each user can only vote once per comment
  CONSTRAINT unique_comment_vote UNIQUE (user_id, comment_id),
  -- A vote must be for either a post OR a comment, not both or neither
  CONSTRAINT vote_target CHECK (
    (post_id IS NOT NULL AND comment_id IS NULL) OR
    (post_id IS NULL AND comment_id IS NOT NULL)
  )
);

-- Create indexes for efficient vote lookups
CREATE INDEX idx_votes_post ON public.votes(post_id) WHERE post_id IS NOT NULL;
CREATE INDEX idx_votes_comment ON public.votes(comment_id) WHERE comment_id IS NOT NULL;
CREATE INDEX idx_votes_user ON public.votes(user_id);

-- Enable Row Level Security
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;

-- Everyone can see all votes (needed for displaying scores)
CREATE POLICY "Users can see all votes"
  ON public.votes FOR SELECT USING (true);

-- Only authenticated users can vote, and only as themselves
CREATE POLICY "Authenticated users can vote"
  ON public.votes FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can change their own votes
CREATE POLICY "Users can change their own votes"
  ON public.votes FOR UPDATE USING (auth.uid() = user_id);

-- Users can remove their own votes
CREATE POLICY "Users can remove their own votes"
  ON public.votes FOR DELETE USING (auth.uid() = user_id);
